name: Deployment pipeline

env: 
  SKIP_CONDITION: ${{ contains(toJson(github.event.commits.*.message), '#skip') }} 

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Run Tests
        run: npm run test
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && env.SKIP_CONDITION != 'true'}}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '20'

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && env.SKIP_CONDITION != 'true'}}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch